config/routes.rb
Rails.application.routes.draw do
  resources :movies do
    resources :ratings, except: [:index, :show]
  end
  resources :sessions
  resources :users

  get 'logout', to: 'sessions#destroy', as: 'logout'

  root 'movies#index'
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]
  helper_method :sort_column, :sort_direction

  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.all.order(sort_column + ' ' + sort_direction).search(search_params).paginate(page: params[:page], per_page: 20)
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)
    @movie.user = current_user if current_user
    add_director
    add_actors
    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    add_director
    add_actors
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    def add_actors
      if !actor_params.blank?
        @movie.cast.destroy_all
        actor_params[:actors].each do |person_id|
          @movie.cast.new(person_id: person_id)
        end
      end
    end

    def add_director
      if !director_params.blank?
        @movie.director.destroy_all
        director_params[:director].each do |person_id|
          @movie.director.new(person_id: person_id)
        end
      end
    end

    def sort_column
      params[:sort] || 'release_date'
    end

    def sort_direction
      params[:direction] || 'desc'
    end

    def movie_params
      params.require(:movie).permit(:title, :description, :release_date, :runtime, :original_rating)
    end

    def director_params
      params.require(:movie).permit(:director => [])
    end

    def actor_params
      params.require(:movie).permit(:actors => [])
    end

    def search_params
      params.permit(:q,:by, :sort, :minrating ,:maxrating)
    end
end

app/helpers/movies_helper.rb
module MoviesHelper
  def current_user_rating
    @movie.ratings.where(user_id: current_user.id)
  end
end

app/views/movies/_form.html.erb
<div class="container">
  <%= form_with(model: movie, local: true) do |form| %>

    <div class="form-group">
      <%= form.label :title %>
      <%= form.text_field :title,class: 'form-control', id: :movie_title %>
    </div>

    <div class="form-group">
      <%= form.label :description %>
      <%= form.text_area :description,class: 'form-control', rows: "3", id: :movie_description %>
    </div>

    <div class="form-group">
      <%= form.label :release_date %>
      <%= form.text_field :release_date,class: 'form-control', id: :movie_release_date %>
    </div>

    <div class="form-group">
      <%= form.label :runtime %>
      <%= form.number_field :runtime,class: 'form-control', id: :movie_runtime %>
    </div>

    <div class="form-group">
      <%= form.label :rating%>
      <%= form.text_field :original_rating,class: 'form-control', id: :movie_original_rating %>
    </div>

    <div class="form-group">
      <%= form.label :director%>
      <%= form.collection_select(:director, Person.all, :id, :name, {include_hidden: false, :selected => movie.director.map(&:person_id)}, {multiple: true, id:'pre-selected-director'}) %>
    </div>

    <div class="form-group">
      <%= form.label :actors%>
      <%= form.collection_select(:actors, Person.all, :id, :name, {include_hidden: false, :selected => movie.cast.map(&:person_id)}, {multiple: true, id:'pre-selected-cast'}) %>
    </div>

      <br>
      <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>
</div>

app/views/movies/edit.html.erb
<h1>Editing Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<h1>List of Movies</h1>
<p> Updated list of upcoming movies.</p>
<% if current_user %>
    <p>If you know about a new movie release, please <%= link_to 'Add a New Movie', new_movie_path %></p>
<% else %>
    <p>If you want to add a new movie, please <%= link_to 'Login', new_session_url %></p>
<% end %>
<br>


<%= form_with url: movies_path, method: :get, local: true do |f| %>
    <%= f.label :q, "Search for:" %>
    <%= f.text_field :q, id: :q %>
    <%= f.select :by, [['Movie title', 0], ['Director', 1], ['Actors', 2]] %>

    <%= f.submit "Search" %>
<% end %>
<div class="space"></div>
<table>
  <thead>
    <tr>
      <th><%= sortable 'title', 'Title' %></th>
      <th><%= sortable 'release_date', 'Release date' %></th>
      <th><%= sortable 'original_rating', 'Rating' %></th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
  <% @movies.each do |movie| %>
      <tr>
        <td><%= movie.title %></td>
        <td><%= movie.release_date %></td>
        <td><%= movie.total_average_rating %></td>
        <td><%= link_to 'Show', movie %>
          <% if current_user && current_user.id == movie.user_id %>
              | <%= link_to 'Edit', edit_movie_path(movie) %> |
              <%= link_to 'Remove', movie, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<%= will_paginate @movies %>


<br>

app/views/movies/new.html.erb
<h1>New Movie</h1>
<div class="space"></div>

<%= render 'form', movie: @movie %>

<br>
<%= link_to 'Back', movies_path %>

<div class="space"></div>

app/views/movies/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @movie.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @movie.description %>
</p>

<p>
  <strong>Release date:</strong>
  <%= @movie.release_date %>
</p>

<p>
  <strong>Average rating:</strong>
  <%= @movie.total_average_rating %>
</p>

<p>
  <strong>TMDB/original rating:</strong>
  <%= @movie.original_rating %>
</p>

<p>
  <strong>User's rating:</strong>
  <%= @movie.users_average_rating %>
</p>

<p>
  <strong>Runtime:</strong>
  <%= @movie.runtime %>
</p>

<p>
  <strong>Director/s:</strong>
  <% @movie.director.each do |director| %>
  <%= director.person.name %>
  <% end %>
</p>


<p>
  <strong>Actors:</strong>
  <% @movie.cast.each do |actor| %>
    <li><%= actor.person.name %></li>
  <% end %>
</p>


<% if current_user && !current_user_rating.blank? %>
    Your rating was <%= current_user_rating.first.rating %>
    <br>
    <%= link_to 'Edit rating', edit_movie_rating_path(@movie,current_user_rating.first)  if current_user %>
    <%= link_to 'Remove', movie_rating_path(@movie,current_user_rating.first), method: :delete, data: { confirm: 'Are you sure?' } if current_user %>
<% else %>
    <%= link_to 'Add rating', new_movie_rating_path(@movie) if current_user %>
<% end %>

<br>
<br>

<% if current_user && current_user.id == @movie.user_id %>
  <%= link_to 'Edit', edit_movie_path(@movie) %> |
<% end %>
<%= link_to 'Back', movies_path %>