config/routes.rb
Rails.application.routes.draw do
  resources :movies do
    resources :ratings, except: [:index, :show]
  end
  resources :sessions
  resources :users

  get 'logout', to: 'sessions#destroy', as: 'logout'

  root 'movies#index'
end

app/views/layouts/_header.html.erb
<div class="navbar">
  <div class="container">
    <div class="logo title-font">
      <h1>
        <%= link_to 'TMDB Upcoming Movies', root_url,  style: 'color:white;text-decoration: none;' %>
      </h1>
    </div>
    <div class="toggle">
      <span></span>
      <span></span>
      <span></span>
      <span></span>
    </div>
    <div class="links">
      <ul>
        <% if current_user %>
            <li><%= link_to "Log out", logout_path %></li>
        <% else %>
            <div id="user_header">
              <li><%= link_to "Sign Up", new_user_path %></li>
              <li><%= link_to "Log In", new_session_path %></li>
            </div>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Moviedb</title>
    <%= csrf_meta_tags %>
    <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>

    <div class="container">
      <div class="row">
        <% if flash[:notice] %>
            <div id="notice"><%= flash[:notice] %></div>
        <% end %>
        <div class="col-md-2 col-sm-1"></div>
        <div class="col-md-8 col-sm-10">
          <%= yield %>
        <div class="col-md-2 col-sm-1"></div>

      </div>
    </div>
  </body>
</html>